<!DOCTYPE html>
<!-- bcarter book.php
   this php which allows the user to interact and enter
   usefuly information about their stay it it then sent to addbooking.php
   through POST and information is stored on cookies which is
   exstracted and put into Xml

 -->
<html>
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" type="text/css" href="css/initBookingForm.css">
        <link rel="stylesheet" type="text/css" href="css/template_live.css">
        <title>booking</title>
        <script src="js/jquery-1.11.3.min.js"></script>
        <script src="js/cookie.js"></script>
        <script src="js/bookRooms.js"></script>
    </head>
    
    <body>
    
        <h1>La Casa Hotel</h1>
            
        <nav>
            <ul id = "nav">
                <li> <a href="index.php">Home</a> </li>
                <li> <a href="rooms.php">View Rooms</a> </li>
                <li id="current"><a>Book a Room</a></li>

            </ul>
        </nav>
        
        
      <div id = "main">  
        <div>
        
            <div id="currentBookings">
                <h2> Pending Bookings </h2>
                
                <ul id="bookingList">
                    
                </ul>
            </div>
            
            <h2> Make a New Booking </h2>
            
            <!--
                Note: There are 3 stages to the booking process
                1) The #findRoomForm is shown to ask for checkin and check out dates.
                   At this stage #searchingForRooms and #bookRoomForm should be hidden
                2) Once the dates have been checked, a search is made for available rooms.
                   The submit button of #findRoomForm is disabled, and #searchingForRooms is shown.
                3) One the search is complete, #searchingForRooms is hidden, and #bookRoomForm is shown.
                   Here the customer can select a room and finish their booking.
            -->
            
            <form id="findRoomForm" action="" method ="POST">
                <p>
                    <!-- Note: Options in the date fields could be generated by JavaScript
                         They could then also prevent invalid dates like 31-Feb being picked -->
                    <label for="checkinday">Check in date:</label>
                    <select name="checkinday" id="checkinday">
                        <option value="01"> 1</option>
                        <option value="02"> 2</option>
                        <option value="03"> 3</option>
                        <option value="04"> 4</option>
                        <option value="05"> 5</option>
                        <option value="06"> 6</option>
                        <option value="07"> 7</option>
                        <option value="08"> 8</option>
                        <option value="09"> 9</option>
                        <option value="10">10</option>
                        <option value="11">11</option>
                        <option value="12">12</option>
                        <option value="13">13</option>
                        <option value="14">14</option>
                        <option value="15">15</option>
                        <option value="16">16</option>
                        <option value="17">17</option>
                        <option value="18">18</option>
                        <option value="19">19</option>
                        <option value="20">20</option>
                        <option value="21">21</option>
                        <option value="22">22</option>
                        <option value="23">23</option>
                        <option value="24">24</option>
                        <option value="25">25</option>
                        <option value="26">26</option>
                        <option value="27">27</option>
                        <option value="28">28</option>
                        <option value="29">29</option>
                        <option value="30">30</option>
                        <option value="31">31</option>
                    </select>
                    <select name="checkinmonth" id="checkinmonth">
                        <option value="01">Jan</option>
                        <option value="02">Feb</option>
                        <option value="03">Mar</option>
                        <option value="04">Apr</option>
                        <option value="05">May</option>
                        <option value="06">Jun</option>
                        <option value="07">Jul</option>
                        <option value="08">Aug</option>
                        <option value="09">Sep</option>
                        <option value="10">Oct</option>
                        <option value="11">Nov</option>
                        <option value="12">Dec</option>
                    </select>
                    <select name="checkinyear" id="checkinyear">
                        <option value="2015">2015</option>
                        <option value="2016">2016</option>
                    </select>
                    <span id="checkinError" class="error"></span>
                </p>
                <p>
                    <label for="checkout">Check out date:</label>
                    <select name="checkoutday" id="checkoutday">
                        <option value="01"> 1</option>
                        <option value="02"> 2</option>
                        <option value="03"> 3</option>
                        <option value="04"> 4</option>
                        <option value="05"> 5</option>
                        <option value="06"> 6</option>
                        <option value="07"> 7</option>
                        <option value="08"> 8</option>
                        <option value="09"> 9</option>
                        <option value="10">10</option>
                        <option value="11">11</option>
                        <option value="12">12</option>
                        <option value="13">13</option>
                        <option value="14">14</option>
                        <option value="15">15</option>
                        <option value="16">16</option>
                        <option value="17">17</option>
                        <option value="18">18</option>
                        <option value="19">19</option>
                        <option value="20">20</option>
                        <option value="21">21</option>
                        <option value="22">22</option>
                        <option value="23">23</option>
                        <option value="24">24</option>
                        <option value="25">25</option>
                        <option value="26">26</option>
                        <option value="27">27</option>
                        <option value="28">28</option>
                        <option value="29">29</option>
                        <option value="30">30</option>
                        <option value="31">31</option>
                    </select>
                    <select name="checkoutmonth" id="checkoutmonth">
                        <option value="01">Jan</option>
                        <option value="02">Feb</option>
                        <option value="03">Mar</option>
                        <option value="04">Apr</option>
                        <option value="05">May</option>
                        <option value="06">Jun</option>
                        <option value="07">Jul</option>
                        <option value="08">Aug</option>
                        <option value="09">Sep</option>
                        <option value="10">Oct</option>
                        <option value="11">Nov</option>
                        <option value="12">Dec</option>
                    </select>
                    <select name="checkoutyear" id="checkoutyear">
                        <option value="2015">2015</option>
                        <option value="2016">2016</option>
                    </select>
                    <span id="checkoutError" class="error"></span>
                </p>
                <p>
                    <input type="submit" name="findRooms" id="findRooms" value="Find rooms">
                </p>
            </form>

            <div id="searchingForRooms">
                <p>Looking for rooms that are available on those dates, please wait...</p>
            </div>

            <form id="bookRoomForm" action="addbooking.php">
                <input type="hidden" id="checkinDate">
                <input type="hidden" id="checkoutDate">
                <p>You have selected a valid check in/out date now Enter:</p>
                <p>
                    <label for="bookingName">Guest name: </label>
                    <input type="text" name="bookingName" id="bookingName">
                    <span id="nameError" class="error"></span>
                </p>
                <p>
                    <label for="roomSelection">Select a room: </label>
                    <select id="roomSelection" name="roomSelection">
                        
                    </select>
                </p>
                <p>
                    <input type="submit" name="bookRoom" id="BookRoom" value = "Book room">
                </p>
            </form>
            

            
                   

            
        </div>
    </div>
        
    </body>
</html>